In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from googleapiclient.discovery import build
import cufflinks as cf
import chart_studio.plotly as py
import plotly.express as px
from plotly.offline import download_plotlyjs,init_notebook_mode,plot,iplot
init_notebook_mode(connected=True)
cf.go_offline()
import plotly.graph_objects as go
import json

In [2]:
df=pd.read_html('https://myfinal11.in/series/vijay-hazare-trophy-122323/records/batting-most-runs/')
df[0].to_csv('batting_vht.csv')
batting_df=pd.read_csv('batting_vht.csv')
batting_df.head(20)

,Unnamed: 0,Player,MAT,INNS,NO,RUNS,HS,AVG,BF,SR,100s,50s,6s,4s
0,0,1. Ruturaj Gaikwad,5,5,1,603,168,150.75,534,112.92,4,-,19,51
1,1,2. Rishi Dhawan,8,8,2,458,91,76.33,360,127.22,-,5,8,52
2,2,3. Prashant Chopra,8,8,-,456,99,57.00,622,73.31,-,5,12,41
3,3,4. Shubham Sharma,6,6,-,418,108,69.67,434,96.31,1,4,4,42
4,4,5. Venkatesh Iyer,6,6,-,379,151,63.17,283,133.92,2,1,21,19
5,5,6. Manan Vohra,5,5,-,379,141,75.80,400,94.75,2,2,6,34
6,6,7. Rinku Singh,7,6,2,379,104,94.75,425,89.18,1,4,6,36
7,7,8. Dinesh Karthik,8,7,-,376,116,53.71,381,98.69,1,2,13,34
8,8,9. Kona Srikar Bharat,5,5,1,370,161,92.50,342,108.19,2,-,15,39
9,9,10. Samit Gohel,6,6,2,358,135,89.50,477,75.05,1,2,5,32
10,10,Player,MAT,INNS,NO,RUNS,HS,AVG,BF,SR,100s,50s,6s,4s
11,11,11. Bishal Ghosh,6,5,3,349,127,174.50,427,81.73,2,1,2,33
12,12,12. Puneet Bisht,5,5,-,334,142,66.80,332,100.60,1,2,1,40
13,13,13. Abhijeet Tomar,6,6,1,333,104,66.60,427,77.99,1,2,6,34
14,14,14. Harpreet Singh,5,5,-,330,113,66.00,408,80.88,2,1,3,31
15,15,15. Chirag Khurana,5,5,1,326,117,81.50,430,75.81,2,2,2,24
16,16,16. Baba Indrajith,8,8,1,325,80,46.43,382,85.08,-,4,4,30
17,17,17. Ravi Chauhan,7,7,-,314,95,44.86,413,76.03,-,2,6,42
18,18,18. Shubham Arora,8,8,1,313,136,44.71,372,84.14,1,1,1,40
19,19,19. Uday Kaul,5,4,1,311,121,103.67,398,78.14,2,-,1,32

In [3]:

index_names = batting_df[ batting_df['Player'] =='Player' ].index
batting_df=batting_df.drop(index_names)

In [5]:
batting_df.replace(to_replace='-',value=0,inplace=True)
batting_df

,Unnamed: 0,Player,MAT,INNS,NO,RUNS,HS,AVG,BF,SR,100s,50s,6s,4s
0,0,1. Ruturaj Gaikwad,5,5,1,603,168,150.75,534,112.92,4,0,19,51
1,1,2. Rishi Dhawan,8,8,2,458,91,76.33,360,127.22,0,5,8,52
2,2,3. Prashant Chopra,8,8,0,456,99,57.00,622,73.31,0,5,12,41
3,3,4. Shubham Sharma,6,6,0,418,108,69.67,434,96.31,1,4,4,42
4,4,5. Venkatesh Iyer,6,6,0,379,151,63.17,283,133.92,2,1,21,19
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
82,82,76. Nazeed Saiyed,5,5,1,178,75,44.50,275,64.73,0,1,4,18
83,83,77. Apoorv Wankhade,3,3,0,177,79,59.00,167,105.99,0,2,7,16
84,84,78. Akshdeep Nath,7,5,0,176,78,35.20,243,72.43,0,1,2,18
85,85,79. Madhav Kaushik,4,4,0,175,89,43.75,231,75.76,0,1,5,16
86,86,80. Aditya Kaushik,5,5,0,175,53,35.00,261,67.05,0,1,3,21

In [ ]:
convert_dict = {'MAT': int,
                'INNS': int,
                'NO':int,
                'RUNS':int,
                'HS':int,
                'AVG':float,
                'BF':int,
                'SR':float,
                '100s':int,
                '50s':int,
                '6s':int,
                '4s':int,
                }
batting_df=batting_df.astype(convert_dict)
batting_df.dtypes

In [ ]:
batting_df[['sr.no','Name']] =batting_df['Player'].str.split(".",expand=True,)
batting_df.drop(columns='sr.no',inplace=True)
batting_df

In [ ]:
batting_df.drop(columns='Player',inplace=True)

In [ ]:
batting_df.head(30)

In [ ]:
# batting_df.loc[batting_df.Name=='Dhruv Shorey']

In [ ]:
batting_df.sort_values(by='RUNS',ascending=False).head(10)
fig=go.Figure()
fig=px.bar(batting_df.sort_values(by='RUNS',ascending=False).head(10),title='Ranji Trophy Highest Runs 2022',height=800,x='Name',y='RUNS',text='RUNS',hover_data=['AVG','RUNS',"HS",'INNS'],color='RUNS')
fig.update_traces(texttemplate='%{text:.3s}',textposition='outside')

In [ ]:
batting_df.sort_values(by='AVG',ascending=False).head(10)
fig=go.Figure()
fig=px.bar(batting_df.sort_values(by='AVG',ascending=False).head(10),title='Ranji Trophy Highest Batting Average 2022',height=1080,width=1080,x='Name',y='AVG',text='AVG',hover_data=['AVG','RUNS',"HS",'INNS'],color='AVG')
fig.update_traces(texttemplate='%{text:.5s}',textposition='outside')

In [ ]:
fig=go.Figure()
fig=px.bar(batting_df.sort_values(by='HS',ascending=False).head(10),title='Ranji Trophy Highest Runs in a Single Match 2022',height=800,x='Name',y='HS',text='HS',hover_data=['AVG','RUNS',"HS",'INNS'],color='HS')
fig.update_traces(texttemplate='%{text:.3s}',textposition='outside')

In [ ]:
fig=go.Figure()
fig=px.bar(batting_df.sort_values(by='100s',ascending=False).head(12),title='Ranji Trophy Most Centuries',height=1080,width=1080,x='Name',y='100s',text='100s',hover_data=['AVG','RUNS',"HS",'INNS','100s'],color='100s')
fig.update_traces(texttemplate='%{text:.1s}',textposition='outside')

In [ ]:
df1=pd.read_html('https://myfinal11.in/series/vijay-hazare-trophy-122323/records/bowling-top-wicket-takers/')
df1[0].to_csv('bowling_vht.csv')
bowling_df=pd.read_csv('bowling_vht.csv')

In [ ]:

index_names = bowling_df[ bowling_df['Player'] =='Player' ].index
bowling_df=bowling_df.drop(index_names)
bowling_df.head(20)

In [ ]:
bowling_df.replace(to_replace='-',value=0,inplace=True)
bowling_df

In [ ]:
bowling_df[['Wickets in BBI','Runs in BBI']] =bowling_df['BBI'].str.split("/",expand=True,)
# bowling_df.drop(columns='sr.no',inplace=True)
# bowling_df.drop(columns='Player',inplace=True)

In [ ]:
convert_dict_2 = {'MAT': int,
                'INNS': int,
                'OVR':float,
                'MD':int,
                'RUNS':int,
                'WK':int,
                'AVG':float,
                'ECN':float,
                'SR':float,
                '5W':int,
                '4W':int,
                'Wickets in BBI':int,
                'Runs in BBI':int,
                }

In [ ]:
bowling_df=bowling_df.astype(convert_dict_2)
bowling_df.dtypes

In [ ]:
bowling_df[['sr.no','Name']] =bowling_df['Player'].str.split(".",expand=True,)
bowling_df.drop(columns='sr.no',inplace=True)
bowling_df.drop(columns='Player',inplace=True)

In [ ]:
best_bowling_figures=bowling_df.sort_values(by='Wickets in BBI',ascending=False).head(10)
# best_bowling_figures
bowling_df.loc[bowling_df['Wickets in BBI']==7 ]

In [ ]:
fig=go.Figure()
fig=px.bar(bowling_df.sort_values(by='WK',ascending=False).head(10),title='Ranji Trophy Highest Wicket Taker 2022',height=800,x='Name',y='WK',text='WK',hover_data=['AVG','RUNS',"ECN",'OVR','WK','BBI','INNS'],color='WK')
fig.update_traces(texttemplate='%{text:.2s}',textposition='outside')

In [ ]:
fig=go.Figure()
fig=px.bar(bowling_df.sort_values(by='ECN',ascending=True).head(10),title='Ranji Trophy Most Ecconomical bowler 2022',height=800,x='Name',y='ECN',text='ECN',hover_data=['AVG','RUNS',"ECN",'OVR','WK','BBI','INNS'],color='ECN')
fig.update_traces(texttemplate='%{text:.3s}',textposition='outside')

In [ ]:
fig=go.Figure()
fig=px.bar(bowling_df.sort_values(by='OVR',ascending=False).head(10),title='Ranji Trophy Most Overs Bowled 2022',height=800,x='Name',y='OVR',text='OVR',hover_data=['AVG','RUNS',"ECN",'OVR','WK','BBI','INNS'],color='OVR')
fig.update_traces(texttemplate='%{text:.4s}',textposition='outside')

In [ ]:
fig=go.Figure()
fig=px.bar(bowling_df.sort_values(by='Wickets in BBI',ascending=False).head(10),title='Ranji Trophy Best Bowling Figures 2022',height=800,x='Name',y='Wickets in BBI',text='Wickets in BBI',hover_data=['AVG','RUNS',"ECN",'OVR','WK','BBI','INNS'],color='Wickets in BBI')
fig.update_traces(texttemplate='%{text:.1s}',textposition='outside')